meta_title: "Le Spécialiste de la remorque Bordeaux"
meta_description: "Vente, location, entretien et atelier de tout type de remorque à Pessac, Bordeaux, Aquitaine"
meta_image: "soumat-remorque-logo-1487954333.jpg" # Une image dans votre dossier app/assets/images/
