# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)



#Usage.create(name: 'Occasionnel')
#Usage.create(name: 'Régulier')
#Usage.create(name: 'Intensif')

#Document.create(name: 'Permis B')
#Document.create(name: 'Permis B96')
#Document.create(name: 'Permis BE')
#Document.create(name: 'Permis C')

#Category.create(name: 'Trailers')
#Category.create(name: 'Accessories')
#Category.create(name: 'Maintenance')
#Category.create(name: 'Installations')
#Category.create(name: 'Documents')

#Brand.create(name: 'IFOR WILLIAMS')
#Brand.create(name: 'LIDOR')
#Brand.create(name: 'HUMBAUR')
#Brand.create(name: 'ERDE EXPERT')
#Brand.create(name: 'MECANOREM')
#Brand.create(name: 'BRENDERUP')
#Brand.create(name: 'NUGENT')
#Brand.create(name: 'ECIM')
#Brand.create(name: 'SUN WAY')

#Subcategory.create(name: 'Bagagères / Utilitaires')
#Subcategory.create(name: 'Nautiques')
#Subcategory.create(name: 'Transports animaliers')
#Subcategory.create(name: 'Porte-engins')
#Subcategory.create(name: 'Porte-moto/quad')
#Subcategory.create(name: 'Remorques plateau')
#Subcategory.create(name: 'Espaces verts')
#Subcategory.create(name: 'Porte-voiture')
#Subcategory.create(name: 'Porte-engins')
#Subcategory.create(name: 'Remorques fourgon')
#Subcategory.create(name: 'Bennes')
#Subcategory.create(name: 'Électricité')
#Subcategory.create(name: 'Attelages')
#Subcategory.create(name: 'Essieux')
#Subcategory.create(name: 'Roues')
#Subcategory.create(name: 'Suspensions / Renforts')
#Subcategory.create(name: 'Bâches')
#Subcategory.create(name: 'Réglages')
#Subcategory.create(name: 'Stabilisation')
#Subcategory.create(name: 'Aide à la manoeuvre')
#Subcategory.create(name: 'Immatriculations')
#Subcategory.create(name: 'Contrôle technique')
#Subcategory.create(name: 'Assurances')

#Product.create(name: "REMORQUE BASCULANTE", price: 990, rent: true, second_hand: false, max_load_weight: 500, empty_weight: 210, category_id: 1, brand_id: 5, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 1230, rent: false, second_hand: false, max_load_weight: 500, empty_weight: 210, category_id: 1, brand_id: 2, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 760, rent: false, second_hand: false, max_load_weight: 500, empty_weight: 210, category_id: 1, brand_id: 1, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 2350, rent: false, second_hand: false, max_load_weight: 500, empty_weight: 210, category_id: 1, brand_id: 1, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 1890, rent: false, second_hand: false, max_load_weight: 500, empty_weight: 165, category_id: 1, brand_id: 4, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 2890, rent: true, second_hand: false, max_load_weight: 500, empty_weight: 189, category_id: 1, brand_id: 6, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 1390, rent: true, second_hand: false, max_load_weight: 500, empty_weight: 165, category_id: 1, brand_id: 3, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 600, rent: true, second_hand: true, max_load_weight: 500, empty_weight: 165, category_id: 1, brand_id: 3, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 1200, rent: true, second_hand: false, max_load_weight: 500, empty_weight: 165, category_id: 1, brand_id: 4, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 3000, rent: true, second_hand: false, max_load_weight: 3500, empty_weight: 565, category_id: 1, brand_id: 5, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 2890, rent: true, second_hand: false, max_load_weight: 500, empty_weight: 165, category_id: 1, brand_id: 6, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 1290, rent: false, second_hand: false, max_load_weight: 500, empty_weight: 310, category_id: 1, brand_id: 4, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 1490, rent: false, second_hand: false, max_load_weight: 500, empty_weight: 310, category_id: 1, brand_id: 7, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 1560, rent: false, second_hand: false, max_load_weight: 500, empty_weight: 165, category_id: 1, brand_id: 8, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 860, rent: false, second_hand: false, max_load_weight: 500, empty_weight: 165, category_id: 1, brand_id: 5, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 880, rent: true, second_hand: false, max_load_weight: 500, empty_weight: 420, category_id: 1, brand_id: 5, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 560, rent: true, second_hand: true, max_load_weight: 500, empty_weight: 420, category_id: 1, brand_id: 6, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 980, rent: true, second_hand: false, max_load_weight: 500, empty_weight: 420, category_id: 1, brand_id: 4, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 1690, rent: true, second_hand: false, max_load_weight: 500, empty_weight: 165, category_id: 1, brand_id: 4, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 4360, rent: false, second_hand: false, max_load_weight: 3500, empty_weight: 565, category_id: 1, brand_id: 3, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 1000, rent: true, second_hand: false, max_load_weight: 500, empty_weight: 165, category_id: 1, brand_id: 4, subcategory_id: 1)
#Product.create(name: "REMORQUE BASCULANTE", price: 890, rent: true, second_hand: true, max_load_weight: 500, empty_weight: 165, category_id: 1, brand_id: 4, subcategory_id: 1)
9
