# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#Category.create(name: 'Trailers')
#Category.create(name: 'Accessories')
#Category.create(name: 'Maintenance')
#Category.create(name: 'Installations')
#Category.create(name: 'Documents')

#Brand.create(name: 'IFOR WILLIAMS')
#Brand.create(name: 'LIDOR')
#Brand.create(name: 'HUMBAUR')
#Brand.create(name: 'ERDE EXPERT')
#Brand.create(name: 'MECANOREM')
#Brand.create(name: 'BRENDERUP')
#Brand.create(name: 'NUGENT')
#Brand.create(name: 'ECIM')
#Brand.create(name: 'SUN WAY')

#Subcategory.create(name: 'Bagagères / Utilitaires')
#Subcategory.create(name: 'Nautiques')
#Subcategory.create(name: 'Transports animaliers')
#Subcategory.create(name: 'Porte-engins')
#Subcategory.create(name: 'Porte-moto/quad')
#Subcategory.create(name: 'Remorques plateau')
#Subcategory.create(name: 'Espaces verts')
#Subcategory.create(name: 'Porte-voiture')
#Subcategory.create(name: 'Porte-engins')
#Subcategory.create(name: 'Remorques fourgon')
#Subcategory.create(name: 'Bennes')
#Subcategory.create(name: 'Électricité')
#Subcategory.create(name: 'Attelages')
#Subcategory.create(name: 'Essieux')
#Subcategory.create(name: 'Roues')
#Subcategory.create(name: 'Suspensions / Renforts')
#Subcategory.create(name: 'Bâches')
#Subcategory.create(name: 'Réglages')
#Subcategory.create(name: 'Stabilisation')
#Subcategory.create(name: 'Aide à la manoeuvre')
#Subcategory.create(name: 'Immatriculations')
#Subcategory.create(name: 'Contrôle technique')
#Subcategory.create(name: 'Assurances')
